### ISSUE TITLE
Exception is thrown and the GUI is frozen after placing a symbol in an already occupied position

### ISSUE THREAD

**Issue by toth2peter** [LikvidJozsi/GitegyletAmoeba#1]
Steps to reproduce:
place the first symbol to the already occupied position

Expected: nothing happens (or a warning is shown)

Current: exeption is thrown and the app freezes

```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    trainer.train(1, map_size=(10, 10), view=graphicalView)
  File "/home/peter/Dropbox/BME/MSc/1.felev/Deep-Learning/NagyHF/GitegyletAmoeba/AmoebaPlayGround/AmoebaTrainer.py", line 17, in train
    games = self.play_all_games(games)
  File "/home/peter/Dropbox/BME/MSc/1.felev/Deep-Learning/NagyHF/GitegyletAmoeba/AmoebaPlayGround/AmoebaTrainer.py", line 45, in play_all_games
    game.step(actions[index])
  File "/home/peter/Dropbox/BME/MSc/1.felev/Deep-Learning/NagyHF/GitegyletAmoeba/AmoebaPlayGround/Amoeba.py", line 52, in step
    raise Exception('Trying to place symbol in position already occupied')
Exception: Trying to place symbol in position already occupied
```

**Comment by LikvidJozsi** [comment]
Thx
